spring:
  application:
    name: unifiedhotels
  profiles:
    active: dev

providers:
  geoapify:
    base-url: https://api.geoapify.com
    api-key: ${GEOAPIFY_API_KEY}
    timeout-ms: ${PROVIDER_TIMEOUT_MS:2500}


